import type {Metadata} from "next";
import {Manrope, Space_Grotesk} from "next/font/google";
import "./globals.css";

const headingFont = Space_Grotesk({
    variable: "--font-family-heading",
})

const normalFont = Manrope({
    variable: "--font-family-normal",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${normalFont.variable} ${headingFont.variable}`}>
        <body>{children}</body>
        </html>
    );
}
